### PR TITLE
Run tests in parallel with paratests (part 2)

### PR DESCRIPTION
**Pull request by Adnan-cds**
This change runs tests using [brianium/paratest](https://github.com/paratestphp/paratest) which executes a few instances of PHPUnit in parallel.

brianium/paratest [does not pass](https://github.com/paratestphp/paratest/issues/103) environment variables to PHPUnit.  Our test runs rely on at least two such variables: SIMPLETEST_BASE_URL and SIMPLETEST_DB.  As a work around, we are inserting the values of these two environment variables into the phpunit.xml.dist file.  This way, these environment variables would be honoured.

I have added one more line to [Paul's original pull request](https://github.com/localgovdrupal/drupal-container/pull/6) and created this one.  I am happy for that one line to go into the original pull request and **this one be not merged**.

With these changes, test runs are taking about 28 minutes to complete compared to 47 minutes without.  When I [originally](https://github.com/localgovdrupal/localgov_paragraphs/runs/1096904645?check_suite_focus=true) tried paratest alongside an SQLite database, it took about 18 minutes.  So there's room for improvement given that we are still using MySQL and not SQLite during test runs.

The key thing to consider about Paratest is the output format of individual tests.  The output format of Paratest is inferior to PHPUnit's built-in [TestDox format](https://phpunit.readthedocs.io/en/9.3/textui.html#testdox) IMHO.  So there is a trade-off between speed and the readability of the test output.  For this reason only, I am raising this pull request to help make a decision and not to immediately merge with the master branch.

FAO @finnlewis @paulpopus @stephen-cox @andybroomfield

### CODE REVIEW

**Comment by finnlewis** [comment]
Nice work - @Adnan-cds and @paulpopus !
I see what you mean about the test output, but speed is probably more valuable. 
I wonder what a failed test looks like in the new Paratest output. As long as that is legible, then I think it's a fair trade!

**Comment by paulpopus** [comment]
Looking good @Adnan-cds thanks for the work on this. ~20 minutes is a major improvement.

**Comment by paulpopus** [comment]
Adding comment for github

Closes localgovdrupal/drupal-container#151

**Comment by Adnan-cds** [comment]
> I wonder what a failed test looks like in the new Paratest output.

You are on the right course :)  Here's a failed run: https://github.com/localgovdrupal/drupal-container/runs/1320533742?check_suite_focus=true#step:5:140.  This failure happened because an earlier version of this pull request did not set the webserver hostname (i.e. http://drupal) properly.  It didn't happen due to any issue of the localgov_alert_banner module.  But it should give you an idea.

**Comment by stephen-cox** [comment]
@Adnan-cds @paulpopus The `sed` command was breaking things for me so I fixed it up to use SQLite and updated the Docker container to add the PHP SQLite package.

Let's see how fast it runs now.

**Comment by Adnan-cds** [comment]
> I fixed it up to use SQLite and updated the Docker container to add the PHP SQLite package.

Thanks Steve.

> Let's see how fast it runs now.

Looks like it has slowed down by a minute :(  The only change I can suggest is to keep the SQLite file in /dev/shm instead of /tmp/.  This is how I tried it since /dev/shm is mapped to memory and is slightly quicker.  I also kept the entire codebase in /dev/shm, but that will involve updating all the workflow files, so let's not do that.

**Comment by Adnan-cds** [comment]
If keeping the SQLite file in /dev/shm doesn't speed up the test run then feel free to drop the SQLite relate changes.

**Comment by stephen-cox** [comment]
Total time is now about 23 minutes with the tests taking ~20 mins. There is a failing alert banner test and I'm not sure if this is because of the changes here or whether this is from somewhere else.

**Comment by finnlewis** [comment]
Nice work @stephen-cox !

**Comment by Adnan-cds** [comment]
> There is a failing alert banner test 

I remember about an Alert banner test failing when I tried paratest for the first time as part of a Github actions workflow on this repo. But it didn't recur in the following runs.  IIRC it was [AdminViewTest.php](https://github.com/localgovdrupal/localgov_alert_banner/blob/master/tests/src/Functional/AdminViewTest.php) that failed.  Unfortunately I can't find that failed test run.  Had I spotted it, you could compare it with what you are seeing now :(

**Comment by Adnan-cds** [comment]
I have reran the test that failed earlier and now [it has passed](https://github.com/localgovdrupal/drupal-container/runs/1359577898?check_suite_focus=true).  This is slightly worrying.  There is a possibility that the parallel test run is occasionally running into [Race conditions](https://en.wikipedia.org/wiki/Race_condition#Software).  If we decide to accept this change, we should be open to the idea of reverting it later if Alert banner tests keep failing unexpectedly now and then.

**Comment by stephen-cox** [comment]
The tests failed occasionally when trying to create a directory as part of the setup to run the tests. I suspect that if tests start at the same time then they're all trying to do similar setup tasks and occasionally get in each others way. I tried setting the tests to run in a random order, but this option is not available to the version of Paratest we're forced to use because of the Drupal Symfony version.

I suggest we merge this and accept that there may be problems running tests. If this becomes an issue we have another look at this. How does that sound @Adnan-cds @finnlewis @paulpopus?

**Review by finnlewis — APPROVED** [review]
Happy to try this for a while. Thanks @stephen-cox

**Comment by Adnan-cds** [comment]
> I suggest we merge this and accept that there may be problems running tests. If this becomes an issue we have another look at this.

As long as we are open to reverting this change later if need be, I am happy for it to be **merged**.  I have just one request that everyone who are running these tests now-a-days or have run them recently (e.g. @andybroomfield, @danchamp, @ekes, @gosia-mlynarczyk) be notified that this is going "live".  That should save us from any potential nasty surprises.  But hopefully that won't happen :)

**Comment by andybroomfield** [comment]
@Adnan-cds i think there is a open ticket to rewrite some of the alert banner tests as they rely on the profile being fully installed. Wonder if that's what's causing it to fail?

**Review by stephen-cox — APPROVED** [review]

**Comment by Adnan-cds** [comment]
> Wonder if that's what's causing it to fail?

I don't know really.  But hopefully not :)

**Comment by Adnan-cds** [comment]
I hope to merge this about 1700 today.  I will make an announcement to the Slack channel soon explaining the pros and cons and what to look out for.  Hope that's okay.

**Pull request merged**
