### PR TITLE
Pin composer at version 1 until such time as the install works with c…

### PR DESCRIPTION
**Pull request by finnlewis**
…omposer 2.

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Steve will have to rebuild the Docker image for this change to the Dockerfile to take effect.

FAO @stephen-cox @finnlewis

**Review by Adnan-cds — APPROVED** [review]
Looks good.  Should solve our problem :)

**Comment by stephen-cox** [comment]
@finnlewis @Adnan-cds @andybroomfield  I think I have fixed this, but we will need to go through all the repos with CI configured and update the GitHub Actions file.

The problem is that the Composer version in GitHub actions is version 2. To use Composer v1 we need to use the version installed in the Docker container. See the diff here: https://github.com/localgovdrupal/drupal-container/pull/10/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88

**Comment by Adnan-cds** [comment]
Looks like the Github actions build VM has switched to Composer 2 only [4 days ago](https://github.com/actions/virtual-environments/commit/fa0558daabee017c29e04796f3eef91f2abf49da#diff-8d528b68ca937dfe5a0194829f0eb2633bc3d7a3105a637ccb534a4da765f7a3L115).  People have [complained](https://github.com/actions/virtual-environments/issues/1924) about it without any resolution.  A potential solution mentioned in that issue is to use shivammathur/setup-php to install composer v1.  I don't have preference for that solution over the changes for this PR given that both involves updating all our test workflow files :(  But I thought I will mention it anyway in case you like it :)

**Comment by finnlewis** [comment]
Thanks @Adnan-cds !
Thanks @stephen-cox !

**Pull request merged**
